### PR TITLE
Automate deployment to GitHub Pages with GitHub Actions

### PR DESCRIPTION
**Pull request by jlumbroso**
This YNAB API Starter Kit is *amazing*!!! It's exactly what is needed to get started, with a comprehensive, non-trivial example.

However, as it is, it assumes that the developer has to already have Node.js installed — and that a local environment is necessary for build. In fact, everything can take place within GitHub, thanks to GitHub (that hosts the code), GitHub Actions (that builds the app) and GitHub Pages (that serves the front-end bundle). There is no need for Heroku or any other third-party provider. In fact, this simplifies the codebase a bit!

My goal has been: **REDUCE FRICTION TO CREATING A NEW APP**. Ideally you would hope:
- any YNABer with an idea can simply generate a new project with a click of a button, and learn only what they need to build their idea;
- any YNABer can offer an application to the community **without having to pay for hosting costs** (or using some Heroku free tier).

Here is a summary of what I have done:
- refactored the codebase to deploy on GitHub Page through GitHub Actions
- rewrote the README.md with a consistent level of guidance, assuming a novice user, and channeling almost a decade of teaching intro CS at university level 😇
- turned the repository into a "template repository" so new apps can be created at the click of a button
- described how to use a custom domain name
- bumped the version to v1.0.3

I think this has the potential to really amplify the impact of this starter project, and I would be happy to help improve this pull-request or answer any of your questions. Let me know what you think!

### CODE REVIEW

**Comment by jlumbroso** [comment]
Thanks for your warm appreciation @shama! I'm standing by for any corrections or clarifications you want!

**Comment by grantcox** [comment]
This looks great to me, thank you for the contribution @jlumbroso!  👍

**Comment by shama** [comment]
Thanks again for taking the time to do this. Very much appreciated!

**Comment by jlumbroso** [comment]
@shama I just wanted to follow up to this pull request to point out a few repository configuration change that are necessary for this to work completely.

As you may have noticed, there is no `gh-pages` branch and [the website is a 404](https://ynab.github.io/ynab-api-starter-kit/). This is just because of a minor configuration error, that the GitHub Actions are unable to commit to the repository because of permissions issue. In my fork, I added my SSH key to the secrets (and that's an alternative), but that's too complicated and I found a simpler way.



FIRST, you need to turn your repository into a "template" — that's what will allow people to spin them off like cookie cutters to bootstrap their own projects. To do that, go to [https://github.com/ynab/ynab-api-starter-kit/settings](https://github.com/ynab/ynab-api-starter-kit/settings) and click "Template repository." Indeed this repo is a starter kit, you don't want people to fork it (because it would always imply that they will commit changes back to you), you want them to be able to use your template as a starting point for projects:
image



SECOND, you need to turn on "Read and write" permission for the `GITHUB_TOKEN` default token of GitHub Actions. This is what will allow [the continuous integration to commit the static generated website](https://github.com/ynab/ynab-api-starter-kit/blob/master/.github/workflows/gh-deploy.yaml#L51-L62):
image

I am happy to report that the permissions are preserved when a templated is created, so this will be seamless to users. I just tried [the instructions myself and worked well](https://jlumbroso.github.io/ynab-sandbox/) 😁

**Comment by shama** [comment]
@jlumbroso Thanks for the tips! I've made those changes.

**Comment by bradymholt** [comment]
A few other needed changes:
- The trigger branch name needed to be updated on the workflow file - a028ba161939bfa967c8c04c31f6ba11243c167e
- The Page config needed to be updated to point to `gh-pages` branch.

The demo site is now working: https://ynab.github.io/ynab-api-starter-kit/

**Pull request merged**
